config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  root to: "posts#index"
  resources :posts

  get '/searches', to: 'posts#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_taggable  #  post.tag_list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  # Index action to render all posts
  def index
    @posts = Post.order("created_at DESC")
  end

  def search
    #binding.pry
    @posts = Post.tagged_with(params[:format])
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    user = current_user
    @post = user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to @post
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :tag_list)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BlogApp
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.navbar-text.pull-right
      - if user_signed_in?
        |  Logged in as 
        strong
          = current_user.email
        | . 
        = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
        |  | 
        = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
      - else
        = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
        |  | 
        = link_to "Login", new_user_session_path, :class => 'navbar-link'
      - if notice
        p.alert.alert-notice
          = notice
      - if alert
        p.alert.alert-error
          = alert
      = yield

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2
        = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |msg|
          li
            = msg
  .form-group
    = f.input :title, class: "form-control"
  .form-group
    = f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control"
  .form-group
    = f.label :tag_list, "タグ（カンマ区切り）"
    br
    = text_field_tag 'post[tag_list]', @post.tag_list.join(',') , "data-role" => "tagsinput"
  .form-group
    = f.button :submit

app/views/posts/_tag_list.html.slim
- tag_list.each do |tag|
  span.label.label-primary
    =link_to tag, searches_path(tag)

app/views/posts/edit.html.slim
h2
  | Edit Post
= render "posts/form"

app/views/posts/index.html.slim
.container
  .col-sm-10.col-sm-offset-1.col-xs-12.blog-content
    - @posts.each do |post|
      .col-xs-12
        .text-center
          h2
            = post.title
          h6
            = render 'posts/tag_list', tag_list: post.tag_list
          h6
            = post.created_at.strftime('%b %d, %Y')
        div
          = raw(post.body).truncate(358)
        .text-center
          = link_to "ブログ詳細へ", post_path(post)
        br

app/views/posts/new.html.slim
h2
  | Create New Post
= render "posts/form"

app/views/posts/search.html.slim
.container
  .col-sm-10.col-sm-offset-1.col-xs-12.blog-content
    - @posts.each do |post|
      .col-xs-12
        .text-center
          h2
            = post.title
          h6
            = render 'posts/tag_list', tag_list: post.tag_list
          h6
            = post.created_at.strftime('%b %d, %Y')
        div
          = raw(post.body).truncate(358)
        .text-center
          = link_to "ブログ詳細へ", post_path(post)
        br

app/views/posts/show.html.slim
.col-sm-11.col-xs-12.blog-content
  h2.text-center
    = @post.title
  h5.text-center
    = render 'posts/tag_list', tag_list: @post.tag_list
  h5.text-center
    = @post.created_at.strftime('%b %d, %Y')
  h5.text-center
    = link_to 'Edit', edit_post_path(@post)
  h5.text-center
    = link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }
  div
    = raw @post.body